# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "theme-app-extension-remix"
client_id = "26b4b87d24e13fc980b84e4ba41f7c32"
application_url = "https://b14b-116-105-225-184.ngrok-free.app"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://b14b-116-105-225-184.ngrok-free.app/auth/callback",
  "https://b14b-116-105-225-184.ngrok-free.app/auth/shopify/callback",
  "https://b14b-116-105-225-184.ngrok-free.app/api/auth/callback",
  "https://b14b-116-105-225-184.ngrok-free.app/.shopify/graphiql/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "tien-dev-store.myshopify.com"
